### ISSUE TITLE
【DB】Draw.ioのエクスポートを自動化したい

### ISSUE THREAD

**Issue by penguin4731** [lit-kansai/dj_system-docs#8]
これでいけるっぽいけど、どうもファイルがコミットされない
```
name: Keep draw.io export synchronized
on:
  push:
    branches:
      - main
    paths:
      - "**.drawio"
      - .github/workflows/drawio-export.yml
concurrency:
  group: drawio-export-${{ github.ref }}
  cancel-in-progress: true
jobs:
  drawio-export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Export drawio files to asciidoctor and png files
        uses: rlespinasse/drawio-export-action@v2
        with:
          path: db
          format: png
          transparent: true

      - name: Get author and committer info from HEAD commit
        uses: rlespinasse/git-commit-data-action@1.3.0
        if: github.ref == 'refs/heads/main'

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          commit_message: "docs: sync draw.io exported files"
          ref: ${{ github.head_ref }}
```
